#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://docs.travis-ci.com/user/languages/php/ for more hints
#
language: php

# use container based infrastructure (no sudo possible)
sudo: false

php: [5.6]

matrix:
    allow_failures:
        - php: 5.6
    fast_finish: true

before_script: composer require simpletest/simpletest

script:
  # start PHP5.4 built-in server in background
  - nohup php -S localhost:8080 -t test/site > php-server.log 2>&1 &
  - php Web/php/test/all_test.php
  - php Web/php/test/altitud_test.php
  - cat php-server.log

# disable notifications
notifications:
  email: false

# reduce commit history of git checkout
git:
  depth: 5