#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://docs.travis-ci.com/user/languages/php/ for more hints
#

#skip the installation step entirely
install: true

language: php
php:
  - '5.6'

