version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py collectstatic && gunicorn mysite.wsgi"
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
