version: '2'
services:
  nginx:
    image: teanocrata/osclb
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    links:
      - web
      - kibana
      - letsencrypt
      - elastic
    environment:
      - OPENSMARTCOUNTRY_DOMAIN=opensmartcountry.com
      - KIBANA_OPENSMARTCOUNTRY_DOMAIN=kibana.opensmartcountry.com
      - ELASTIC_OPENSMARTCOUNTRY_DOMAIN=elastic.opensmartcountry.com
    volumes:
      - ./.htpasswd:/etc/nginx/conf.d/.htpasswd
    volumes_from:
      - letsencrypt
  db:
    image: postgres
    container_name: db
    expose:
      - "5432"
    volumes:
      - postgres-db-volume:/usr/share/postgres/data
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=osc.settings.cpd.app_settings
    build: .
    command: bash -c "python manage.py collectstatic --noinput && gunicorn osc_site.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    links:
      - db
      - elastic
    container_name: web
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
    container_name: elastic
    environment:
      - cluster.name=osc-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - path.repo=["/usr/share/elasticsearch/backups"]
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 8g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esbackup:/usr/share/elasticsearch/backups
    expose:
      - 9300
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.0
    container_name: kibana
    environment:
      - XPACK_SECURITY_ENABLED=false
    expose:
      - 5601
    links:
      - elastic:elasticsearch
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    command:  bash -c "sleep 6 && certbot certonly --standalone -d opensmartcountry.com -d kibana.opensmartcountry.com -d elastic.opensmartcountry.com --text --agree-tos --email george@opsrobot.co.uk --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt
      - /var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm

volumes:
  postgres-db-volume:
    external: true
  esdata:
    external: true
  esbackup:
    external: true
