version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && gunicorn osc_site.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
