# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 21:52
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from osc.models import UserProfile


def create_roles_and_profiles(apps, schema_editor):
    for user in User.objects.all():
        Token.objects.get_or_create(user=user)
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('osc', '0002_userparcel_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_roles_and_profiles),
    ]
