# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osc', '0003_auto_20161126_2252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userparcel',
            unique_together=set([('user', 'cadastral_code')]),
        ),
    ]
