# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osc', '0004_auto_20161203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture_link',
            field=models.URLField(null=True),
        ),
    ]
